#!/bin/bash
#set -e

export SLG_VERSION=0.0.1
if [ $# -eq 1 ]; then if [ $1 == "--version" ]; then echo "strandedLibraryGrade version ${SGL_VERSION}, 20220916" ; exit ; fi ; fi

SCRIPTDIR=$( dirname $0 )
export COLLAPSE=${SCRIPTDIR}/utils/collapse.py
export BT2=${SCRIPTDIR}/third_party/minimap2/minimap2



function help {
  echo "     
	 STRANDED LIBRARY GRADE

                                   [mate2]->
          Forward Strand ----------------------------------------------->
                         <---------------------------------------------- Reverse Strand	 
		                                <-[mate1]


	strandedLibraryGrade ${SLG_VERSION}

	Usage:

	If you already have the RNA-seq alignments in BAM format:
		strandedLibraryGrade -b /path/to/alignments.bam [] 

	If you have transcript FASTA and paired reads produced by dUTP method of RNA-seq:
		strandedLibraryGrade -t /path/to/transcripts.fasta -1 /path/to/R1.fastq.gz -2 /path/to/R2.fastq.gz [-m]

	If you have transcript FASTA and unpaired reads produced by dUTP method of RNA-seq:
		strandedLibraryGrade -t /path/to/transcripts.fasta -U /path/to/R1.fastq.gz [-m]



	Options:

	-b	BAMMODE : Input BAM. Alignments should be produced in a stranded-naive way. 
			  Thus, where relevant, do not tell alignmer the strandedness and/or orientation you expect. 
			  Can be SAM format as well. SAMtools will aut-detect.
			  Not compatible with -t/-1/-2/-U.
	-t	FULLMODE: Bowtie2-indexed transcript (query) sequences. Also need -1/-2 or -U. Not compatible with -b.
			  To make, do: 
				bowtie2-build transcripts.fasta transcripts
			  Provide /Path/to/bt2_index_prefix.
			  In above example that would be /Path/to/transcripts
	-1	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b and -U.
	-2	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b and -U.
	-U	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b, -1, and -2.
	-m	Optional. Provide /Path/to/desired/bowtie2. Default: looks in environment.
	-O	Output prefix. Outputs are PREFIX.transcript-summaries.txt and PREFIX.final-summary.txt. Default prefix: strandedLibraryGradeOutput.
	-P	Number of parallel threads. Only applies to bowtie2 step in FULLMODE. Default = 2.
	-S	Skip this many reads before processing. Currently only applies to bowtie2 step in FULLMODE. Default = 0.
	-N	Only analyze this many reads. Currently only applies to bowtie2 step in FULLMODE. Default = all (1000000000).
	-X	Max insert size (i.e. max fragment size). Currently only applies to bowtie2 step in FULLMODE with PAIRED reads. Default = 600.

	Dependencies:
	- Bowtie2
	- BEDtools
	- SAMtools
	- Awk

	Pipeline notes:
	  FULL-MODE:
	  Internally, Bowtie2 is used in an --end-to-end --very-fast* mode. 
		  * similar to --very-fast but with tweaks to increase speed further.
	  Moreover, bowtie2 is given --no-unal --no-contain --no-mixed --no-discordant.
	  This is done since SAMtools is used anyway to filter for only confidently-mapped concordant read pairs ( -f3 -F4 -q 30).
	  Overall, the goal is to evaluate the quality of the library prep.
	  Things like low MAPQ or discordance can arise due to things like algorithmic choices and reference quality.
	  Hence, we use only high confidence concordant alignments to judge the strandedness of the library.


	Use cases:
	- Created RNA-seq library through the dUTP method (most stranded library prep kits).
		- Expect the strandedness to be "ISR" as determined by Salmon.
			- I = inward-facing.
			- S = strand-specific.
			- R = mate1 maps to reverse strand (i.e. the reverse complement of the transcript sequence).

	Citation:
	- This script was developed to evaluate the quality of strand-specific library preps (from NEB and Illumina) for studying DNA Puffs in Bradysia coprophila.
	- It is free to use, further develop, criticize, etc.
	- Feel free to cite this github repo if you find it helpful in your own research.



	Output:
		- transcript-summaries.txt
			- For each transcript, it outputs a 4-column line: 
				1. sequence name, 
				2. total number of confidently-mapped concordant read pairs mapping to it, 
				3. number of those pairs in proper strandedness: mate1 on rev strand. 
				4. proportion pairs with mate1 on rev strand. That is col3/col2.
				- This proportion is the strand-specificity score for that particular transcript.
				- It ranges from 0 to 1, 0 being the worst, 1 being perfect.
				- >90% of transcripts should have scores >0.9
					- some transcripts with very few reads mapping to them are often the culprits for having low scores.
			- The last line is the global library score. It is named \"all\".
				- Columns 2, 3, and 4 are analogous to above only using confidently-mapped concordant read pairs mapping to all transcripts.
		- final-summary.txt
			- This is a 2-column tabular text file: 
				1. metric name
				2. metric score
			- Example:
				-	3535634				## line1: number confidently-mapped concordant pairs with mate1 mapped to reverse strand.
				+	12980				## line2: number confidently-mapped concordant pairs with mate1 mapped to forward strand.   
				pairs	3548614				## line3: total number of confidently-mapped concordant pairs encountered.
				strandbias	0.996342		## line4: line1/line3. should be same as column4 in last line (column1=all) of transcript-summaries.txt.
				perfectBiasTranscripts	9389		## line5: number of transcripts encountered with perfect strand-specificity scores of 1.
				biasedTranscripts	9726		## line6: number of transcripts encountered with strand-specificity scores exceeding 0.9.
				nTranscripts	9993			## line7: total number of transcripts encountered.
				perfectBiasScore	0.939558	## line8: line5/line7. Proportion of transcripts encountered with perfect strand-specificity scores of 1.
				transBiasScore	0.973281		## line9: line6/line7. Proportion of transcripts encountered with strand-specificity scores exceeding 0.9.
			- Brief comments on scores:
				- strandbias:		This is the strandedLibraryGrade. It is a reflection of the strand-specificity of the reads and library itself.
				- perfectBiasScore:	This is a joint-reflection of the library and the quality of the reference transcripts.
				- transBiasScore:	Same as perfectBiasScore, but more lenient.
			- Further info on the scores:
				- All three scores are jointly affected by 
					(i) experimental factors: factors upstream of analysis such as the strand-specificity of the library and sequencing, 
					(ii) introduced factors: algorithmic choices, and reference quality.
				- The "strandbias" gives all condidently-mapped concordant read pairs equal weights regardless of which transcript they map to.
					- Therefore, "strandbias" is weighted much more heavily towards "experimental factors". 
				- The perfectBiasScore and transBiasScore give all transcripts equal weights. 
					- Thus each transcript strand-specificity score is treated with equal confidence regardless of how few or many read pairs map to it.
						- And regardless of how low or high quality the reference transcript sequence is...
					- This weights the summary scores more heavily towards "introduced factors".
					- Indeed, the transcripts with low strand-specificity scores may be suspect that should be flagged for manual annotation review and curation.
						- They may also reflect regions of the genome with genes on both strands.
					- Note that these scores can be interpreted as quantiles or percentiles over the transcripts.
						- perfectBiasScore : the highest quantile one could ask for that would still return 1.
						- transBiasScore   : the highest quantile one could ask for that would still return >0.9.
		
"
}


## HELP CATCH NO ARGS
###################################################################################################################################################################################
if [ $# -eq 0 ]; then help ; exit ; fi
###################################################################################################################################################################################


##############################################################################
## DEFAULTS
##############################################################################
INPUT_BAM=""
TRANS=""
CLEAN=true
R1=""
R2=""
BT2=$( which bowtie2 )
PAIRED=""
FULLMODE=false
BAMMODE=false
OUTPRE="strandedLibraryGradeOutput"
THREADS=2
SKIP=0
NREADS=1000000000
MAXINS=600
HELP=false


ALLVARS="INPUT_BAM TRANS CLEAN R1 R2 BT2 PAIRED FULLMODE BAMMODE"


##############################################################################
## GET OPTS
##############################################################################
while getopts "b:t:1:2:U:m:P" arg; do
    case $arg in
        b) INPUT_BAM=${OPTARG} ; BAMMODE=true ;;
	t) TRANS=${OPTARG} ; FULLMODE=true ;;
	1) R1=${OPTARG} ; FULLMODE=true ; PAIRED=true ;;
	2) R2=${OPTARG} ; FULLMODE=true ; PAIRED=true ;;
	U) R1=${OPTARG} ; FULLMODE=true ; PAIRED=false ;;
	m) BT2=${OPTARG} ;;
	O) OUTPRE=${OPTARG} ;;
	P) THREADS=${OPTARG} ;;
	S) SKIP=${OPTARG} ;;
	N) NREADS=${OPTARG} ;;
	X) MAXINS=${OPTARG} ;;
        *) help; exit;;
    esac
done

####m) if [ ${OPTARG} == "which" ]; then MINIMAP2=$( which minimap2 ); else MINIMAP2=${OPTARG} ; fi ;;


## HELP CATCHALL <<not nec code given above>>
###################################################################################################################################################################################
if [ $# -eq 0 ]; then help ; exit ; fi
if $FULLMODE && $BAMMODE; then echo "Specify only either -i or -t/-1/-2/-U" ; help ; exit ; fi
if $BAMMODE ; then if [ -z $INPUT_BAM ]; then echo "Something is wrong. BAM mode on, but not BAM found." ; help; exit ; fi ; fi
if $FULLMODE && $PAIRED ; then for VAR in TRANS R1 R2 BT2 ; do if [ -z ${!VAR} ] ; then echo "Something is wrong. Full paired mode on, but ${VAR} not found." ; help; exit ; fi ; done ; fi
if $FULLMODE && ! $PAIRED ; then for VAR in TRANS R1 BT2 ; do if [ -z ${!VAR} ] ; then echo "Something is wrong. Full paired mode on, but ${VAR} not found." ; help; exit ; fi ; done ; fi

###################################################################################################################################################################################

echo DEBUG: 1>&2
for VAR in ${ALLVARS} ; do echo -e "${VAR}\t${!VAR}" 1>&2 ; done

##############################################################################
## FUNCTIONS
##############################################################################


function mapPairedReads {
  ${BT2} --skip ${SKIP} --upto ${NREADS} --maxins ${MAXINS} --no-unal --no-contain --no-mixed --no-discordant --end-to-end -D 2 -R 0 -N 0 -L 32 -i S,0,5 -p 8 -x ${BT2TIDX} -1 ${R1} -2 ${R2} 
}

function mapUnpairedReads {
  ${BT2} --skip ${SKIP} --upto ${NREADS} --no-unal --no-discordant --end-to-end -D 2 -R 0 -N 0 -L 32 -i S,0,5 -p 8 -x ${BT2TIDX} -U ${R1} 
}

function samFilter {
  #samtools view -bSh -f 3 -F 4 -q 30 ${1}
  samtools view -bh -f 3 -F 4 -q 30 ${1}
}

function bam2bedpe {
  if [ $# -eq 0 ]; then IN="-" ; else IN=${1} ; fi
  bamToBed -mate1 -bedpe -i ${1}
}

function transcriptSummaries {
  awk 'BEGIN{all=0 ; allneg=0 }
      {all+=1 ; total[$1]+=1 ; if($9=="-"){neg[$1]+=1 ; allneg+=1 }else{neg[$1]+=0}}
      END{ for (e in total) print e"\t"total[e]"\t"neg[e]"\t"neg[e]/total[e] ; print "all\t"all"\t"allneg"\t"allneg/all}' ${1}
####> ${TRANS}
}

function finalSummary {
  awk '{if ($4==1){one+=1} ; 
        if ($4>0.9){bias+=1} ; 
        if ($1=="all"){readcount=$2 ; negcount=$3 ; poscount=$2-$3 ; readscore=$4}else{all+=1}}
        END{OFS="\n" ; print "-\t"negcount, 
                             "+\t"poscount, 
                             "pairs\t"readcount, 
                             "strandbias\t"readscore, 
                             "perfectBiasTranscripts\t"one, 
                             "biasedTranscripts\t"bias, 
                             "nTranscripts\t"all, 
                             "perfectBiasScore\t"one/all, 
                             "transBiasScore\t"bias/all}' ${1}  
###> ${SUMMA}
}

function gradeBam {
	samFilter ${BAM} | bam2bedpe | transcriptSummaries
}

function gradePairedReads {
  mapPairedReads | gradeBam
}

function gradeUnpairedReads {
  mapUnpairedReads | gradeBam
}


##function strandedLibraryGrade 





##############################################################################
## EXECUTE ..... FINAL FUNCTION ASSIGNMENT
##############################################################################
## VARIABLE FUDGING
BAM=${INPUT_BAM}
BT2TIDX=${TRANS}

if $BAMMODE ; then
  export FXN=gradeBam
elif $FULLMODE ; then
  if $PAIRED ; then export FXN=gradePairedReads ;
  else export FXN=gradeUnpairedReads 
  fi
else
  echo "DEBUG::: Something wrong..... FXN assignment" ; exit
fi



##############################################################################
## EXECUTE
##############################################################################
OUT1=${OUTPRE}.transcript-summaries.txt
OUT2=${OUTPRE}.final-summary.txt
${FXN} > ${OUT1}
finalSummary ${OUT1} > ${OUT2}
