#!/bin/bash
#set -e

export SLG_VERSION=0.0.1
if [ $# -eq 1 ]; then if [ $1 == "--version" ]; then echo "strandedLibraryGrade version ${SGL_VERSION}, 20220916" ; exit ; fi ; fi

SCRIPTDIR=$( dirname $0 )
export COLLAPSE=${SCRIPTDIR}/utils/collapse.py
export BT2=${SCRIPTDIR}/third_party/minimap2/minimap2



function help {
  echo "     
	 STRANDED LIBRARY GRADE

                                   [mate2]->
          Forward Strand ----------------------------------------------->
                         <---------------------------------------------- Reverse Strand	 
		                                <-[mate1]


	strandedLibraryGrade ${SLG_VERSION}

	Usage:

	If you already have the RNA-seq alignments in BAM format:
		strandedLibraryGrade -b /path/to/alignments.bam [-u] 

	If you have transcript FASTA and paired reads produced by dUTP method of RNA-seq:
		strandedLibraryGrade -t /path/to/transcripts.fasta -1 /path/to/R1.fastq.gz -2 /path/to/R2.fastq.gz [-m] [-O prefix] [-P threads] [ -S skip ] [-N nreads ] [-X maxins ]

	If you have transcript FASTA and unpaired reads produced by dUTP method of RNA-seq:
		strandedLibraryGrade -t /path/to/transcripts.fasta -U /path/to/R1.fastq.gz [-m] [-O prefix] [-P threads] [ -S skip ] [-N nreads ] [-X maxins ]

	If you have a config text file specifying file locations of many BAMs or Fastqs (as explained below). All need to be same type (paired or unpaired).
		strandedLibraryGrade -f /path/to/samples.txt [-u] [-m] [-O prefix] [-P threads] [ -S skip ] [-N nreads ] [-X maxins ]
	

	Options:

	-b	BAMMODE : Input BAM. Alignments should be produced in a stranded-naive way. 
			  Thus, where relevant, do not tell alignmer the strandedness and/or orientation you expect. 
			  Can be SAM format as well. SAMtools will aut-detect.
			  Not compatible with -t/-1/-2/-U.
	-u	BAMMODE: BAM was produced by mapping single-end unpaired reads. Default: false (assumed paired). Also may need to use this for FOFNMODE when using file full of single-end BAMs.
	-t	FULLMODE: Bowtie2-indexed transcript (query) sequences. Also need -1/-2 or -U. Not compatible with -b.
			  To make, do: 
				bowtie2-build transcripts.fasta transcripts
			  Provide /Path/to/bt2_index_prefix.
			  In above example that would be /Path/to/transcripts
			  NOTE: also needed in FOFNMODE for fastq files.
	-1	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b and -U.
	-2	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b and -U.
	-U	FULLMODE: Mate1 reads from paired reads. Provide: /path/to/R1.fastq.gz. Not compatible with -b, -1, and -2.
	-m	Optional. Provide /Path/to/desired/bowtie2. Default: looks in environment.
	-O	Output prefix. Outputs are PREFIX.transcript-summaries.txt and PREFIX.final-summary.txt. Default prefix: strandedLibraryGradeOutput.
	-P	Number of parallel threads. Only applies to bowtie2 step in FULLMODE. Default = 2.
	-S	Skip this many reads before processing. Currently only applies to bowtie2 step in FULLMODE. Default = 0.
	-N	Only analyze this many reads. Currently only applies to bowtie2 step in FULLMODE. Default = all (1000000000).
	-X	Max insert size (i.e. max fragment size). Currently only applies to bowtie2 step in FULLMODE with PAIRED reads. Default = 600.
	-f	FOFNMODE: Process multiple samples serially.
			Specify /path/to/samples.txt, a tab-delimited text file with 2-3 columns:
			column1 = output prefix
			column2 = R1 fastq (can be gz) or BAM. Note: if BAM of single-end reads, specify -u. If FASTQ, need to specify -t.
			column3 = R2 fastq. Optional column for FULLMODE. Note: make sure to specify -t.
	-v	Verbose. Say stuff. Only does stuff during FOFN mode at the moment.

	Dependencies:
	- Bowtie2
	- BEDtools
	- SAMtools
	- Awk

	Pipeline notes:
	  FULL-MODE:
	  Internally, Bowtie2 is used in an --end-to-end --very-fast* mode. 
		  * similar to --very-fast but with tweaks to increase speed further.
	  Moreover, bowtie2 is given --no-unal --no-contain --no-mixed --no-discordant.
	  This is done since SAMtools is used anyway to filter for only confidently-mapped concordant read pairs ( -f3 -F4 -q 30).
	  Overall, the goal is to evaluate the quality of the library prep.
	  Things like low MAPQ or discordance can arise due to things like algorithmic choices and reference quality.
	  Hence, we use only high confidence concordant alignments to judge the strandedness of the library.


	Use cases:
	- Created RNA-seq library through the dUTP method (most stranded library prep kits).
		- Expect the strandedness to be "ISR" as determined by Salmon.
			- I = inward-facing.
			- S = strand-specific.
			- R = mate1 maps to reverse strand (i.e. the reverse complement of the transcript sequence).

	Citation:
	- This script was developed to evaluate the quality of strand-specific library preps (from NEB and Illumina) for studying DNA Puffs in Bradysia coprophila.
	- It is free to use, further develop, criticize, etc.
	- Feel free to cite this github repo if you find it helpful in your own research.



	Output:
		- transcript-summaries.txt
			- For each transcript, it outputs a 4-column line: 
				1. sequence name, 
				2. total number of confidently-mapped concordant read pairs mapping to it, 
				3. number of those pairs in proper strandedness: mate1 on rev strand. 
				4. proportion pairs with mate1 on rev strand. That is col3/col2.
				- This proportion is the strand-specificity score for that particular transcript.
				- It ranges from 0 to 1, 0 being the worst, 1 being perfect.
				- >90% of transcripts should have scores >0.9
					- some transcripts with very few reads mapping to them are often the culprits for having low scores.
			- The last line is the global library score. It is named \"all\".
				- Columns 2, 3, and 4 are analogous to above only using confidently-mapped concordant read pairs mapping to all transcripts.
		- final-summary.txt
			- This is a 2-column tabular text file: 
				1. metric name
				2. metric score
			- Example:
				-	3535634				## line1: number confidently-mapped concordant pairs with mate1 mapped to reverse strand.
				+	12980				## line2: number confidently-mapped concordant pairs with mate1 mapped to forward strand.   
				pairs	3548614				## line3: total number of confidently-mapped concordant pairs encountered.
				strandbias	0.996342		## line4: line1/line3. should be same as column4 in last line (column1=all) of transcript-summaries.txt.
				perfectBiasTranscripts	9389		## line5: number of transcripts encountered with perfect strand-specificity scores of 1.
				biasedTranscripts	9726		## line6: number of transcripts encountered with strand-specificity scores exceeding 0.9.
				nTranscripts	9993			## line7: total number of transcripts encountered.
				perfectBiasScore	0.939558	## line8: line5/line7. Proportion of transcripts encountered with perfect strand-specificity scores of 1.
				transBiasScore	0.973281		## line9: line6/line7. Proportion of transcripts encountered with strand-specificity scores exceeding 0.9.
			- Brief comments on scores:
				- strandbias:		This is the strandedLibraryGrade. It is a reflection of the strand-specificity of the reads and library itself.
				- perfectBiasScore:	This is a joint-reflection of the library and the quality of the reference transcripts.
				- transBiasScore:	Same as perfectBiasScore, but more lenient.
			- Further info on the scores:
				- All three scores are jointly affected by 
					(i) experimental factors: factors upstream of analysis such as the strand-specificity of the library and sequencing, 
					(ii) introduced factors: algorithmic choices, and reference quality.
				- The "strandbias" gives all condidently-mapped concordant read pairs equal weights regardless of which transcript they map to.
					- Therefore, "strandbias" is weighted much more heavily towards "experimental factors". 
				- The perfectBiasScore and transBiasScore give all transcripts equal weights. 
					- Thus each transcript strand-specificity score is treated with equal confidence regardless of how few or many read pairs map to it.
						- And regardless of how low or high quality the reference transcript sequence is...
					- This weights the summary scores more heavily towards "introduced factors".
					- Indeed, the transcripts with low strand-specificity scores may be suspect that should be flagged for manual annotation review and curation.
						- They may also reflect regions of the genome with genes on both strands.
					- Note that these scores can be interpreted as quantiles or percentiles over the transcripts.
						- perfectBiasScore : the highest quantile one could ask for that would still return 1.
						- transBiasScore   : the highest quantile one could ask for that would still return >0.9.
		
"
}


## HELP CATCH NO ARGS
###################################################################################################################################################################################
if [ $# -eq 0 ]; then help ; exit ; fi
###################################################################################################################################################################################


##############################################################################
## DEFAULTS
##############################################################################
export INPUT_BAM=""
export TRANS=""
export CLEAN=true
export R1=""
export R2=""
export BT2=$( which bowtie2 )
export PAIRED=true
export RTYPE=pairs
export FULLMODE=false
export BAMMODE=false
export FOFNMODE=false
export OUTPRE="strandedLibraryGradeOutput"
export THREADS=2
export SKIP=0
export NREADS=1000000000
export MAXINS=600
export HELP=false
export VERBOSE=false

export ALLVARS="INPUT_BAM TRANS CLEAN R1 R2 BT2 PAIRED RTYPE FULLMODE BAMMODE FOFNMODE OUTPRE THREADS NREADS MAXINS"


##############################################################################
## GET OPTS
##############################################################################
while getopts "b:ut:1:2:U:m:P:S:N:X:f:v" arg; do
    case $arg in
        b) export INPUT_BAM=${OPTARG} ; export BAMMODE=true ;;
	u) export PAIRED=false ; export RTYPE=reads ;;
	t) export TRANS=${OPTARG} ; export FULLMODE=true ;;
	1) export R1=${OPTARG} ; export FULLMODE=true ; export PAIRED=true ; export RTYPE=pairs ;;
	2) export R2=${OPTARG} ; export FULLMODE=true ; export PAIRED=true ; export RTYPE=pairs ;;
	U) export R1=${OPTARG} ; export FULLMODE=true ; export PAIRED=false ; export RTYPE=reads ;;
	m) export BT2=${OPTARG} ;;
	O) export OUTPRE=${OPTARG} ;;
	P) export THREADS=${OPTARG} ;;
	S) export SKIP=${OPTARG} ;;
	N) export NREADS=${OPTARG} ;;
	X) export MAXINS=${OPTARG} ;;
	f) export FOFN=${OPTARG} ; FOFNMODE=true ;;
	v) export VERBOSE=true ;;
        *) help; exit;;
    esac
done



## HELP CATCHALL <<not nec code given above>>
###################################################################################################################################################################################
if [ $# -eq 0 ]; then help ; exit ; fi

echo DEBUG:: PARSED OPTIONS 1>&2 ; for VAR in ${ALLVARS} ; do echo -e "${VAR}\t${!VAR}" 1>&2 ;  done ; echo 1>&2

if $FULLMODE && $BAMMODE; then echo "Specify only either -i or -t/-1/-2/-U" ; help ; exit ; fi
if $BAMMODE ; then if [ -z $INPUT_BAM ]; then echo "Something is wrong. BAM mode on, but not BAM found." ; help; exit ; fi ; fi
if $FULLMODE && $PAIRED && ! $FOFNMODE ; then for VAR in TRANS R1 R2 BT2 ; do if [ -z ${!VAR} ] ; then echo "Something is wrong. Full paired mode on, but ${VAR} not found." ; help; exit ; fi ; done ; fi
if $FULLMODE && ! $PAIRED && ! $FOFNMODE ; then for VAR in TRANS R1 BT2 ; do if [ -z ${!VAR} ] ; then echo "Something is wrong. Full unpaired mode on, but ${VAR} not found." ; help; exit ; fi ; done ; fi
if $FOFNMODE ; then INSPECT=( $( head -n 1 $FOFN ) ) ; if [ ${INSPECT[1]: -4} == ".bam" ]; then export BAMMODE=true ; else export FULLMODE=true ; fi ; fi
if $FOFNMODE && $FULLMODE ; then if [ -z ${TRANS} ]; then echo "FOFN mode specified, BAMs not found in column2 of ${FOFN}, so FULLMODE assumed yet no bowtie2 index provided with -t. Try again. Exiting..." ; help ; exit ; fi ; fi
if $FOFNMODE && $BAMMODE && $PAIRED ; then echo "WARN: assuming BAMs are from paired-end reads. If single-end reads, please specify -u. Script may die in flames." 1>&2 ; fi 

###################################################################################################################################################################################

echo DEBUG:: FURTHER PROCESSED OPTIONS 1>&2 ; for VAR in ${ALLVARS} ; do echo -e "${VAR}\t${!VAR}" 1>&2 ;  done ; echo 1>&2


##############################################################################
## FUNCTIONS
##############################################################################


function mapPairedReads {
  ${BT2} --skip ${SKIP} --upto ${NREADS} --maxins ${MAXINS} --no-unal --no-contain --no-mixed --no-discordant --end-to-end -D 2 -R 0 -N 0 -L 32 -i S,0,5 -p ${THREADS} -x ${BT2TIDX} -1 ${R1} -2 ${R2} 
}

function mapUnpairedReads {
  ${BT2} --skip ${SKIP} --upto ${NREADS} --no-unal --no-discordant --end-to-end -D 2 -R 0 -N 0 -L 32 -i S,0,5 -p ${THREADS} -x ${BT2TIDX} -U ${R1} 
}

function samFilter {
  #samtools view -bSh -f 3 -F 4 -q 30 ${1}
  samtools view -bh -f 3 -F 4 -q 30 ${1}
}

function samFilterSE {
  #samtools view -bSh -f 3 -F 4 -q 30 ${1}
  samtools view -bh -F 4 -q 30 ${1}
}

function bam2bedpe {
  if [ $# -eq 0 ]; then IN="-" ; else IN=${1} ; fi
  bamToBed -mate1 -bedpe -i ${1}
}

function bam2bedse {
  if [ $# -eq 0 ]; then IN="-" ; else IN=${1} ; fi
  bamToBed -i ${1} | awk 'OFS="\t" {print $1,$2,$3,$4,$5,".",".",".",$6}'
}

function transcriptSummaries {
  awk 'BEGIN{all=0 ; allneg=0 }
      {all+=1 ; total[$1]+=1 ; if($9=="-"){neg[$1]+=1 ; allneg+=1 }else{neg[$1]+=0}}
      END{ for (e in total) print e"\t"total[e]"\t"neg[e]"\t"neg[e]/total[e] ; print "all\t"all"\t"allneg"\t"allneg/all}' ${1}
####> ${TRANS}
}

function finalSummary {
  awk -v "TYPE=${RTYPE}" '{if ($4==1){one+=1} ; 
        if ($4>0.9){bias+=1} ; 
        if ($1=="all"){readcount=$2 ; negcount=$3 ; poscount=$2-$3 ; readscore=$4}else{all+=1}}
        END{OFS="\n" ; print "-\t"negcount, 
                             "+\t"poscount, 
                             TYPE"\t"readcount, 
                             "strandbias\t"readscore, 
                             "perfectBiasTranscripts\t"one, 
                             "biasedTranscripts\t"bias, 
                             "nTranscripts\t"all, 
                             "perfectBiasScore\t"one/all, 
                             "transBiasScore\t"bias/all}' ${1}  
###> ${SUMMA}
}

function gradeBam {
	samFilter ${BAM} | bam2bedpe | transcriptSummaries
}

function gradeBamSE {
  samFilterSE ${BAM} | bam2bedse | transcriptSummaries
}

function gradePairedReads {
  mapPairedReads | gradeBam
}

function gradeUnpairedReads {
  mapUnpairedReads | gradeBamSE
}


##function strandedLibraryGrade 





##############################################################################
## EXECUTE ..... FINAL FUNCTION ASSIGNMENT
##############################################################################
## VARIABLE FUDGING
BAM=${INPUT_BAM}
BT2TIDX=${TRANS}

if $BAMMODE ; then
  if $PAIRED; then export FXN=gradeBam ;
  else export FXN=gradeBamSE ;
  fi
elif $FULLMODE ; then
  if $PAIRED ; then export FXN=gradePairedReads ;
  else export FXN=gradeUnpairedReads 
  fi
else
  echo "DEBUG::: Something wrong..... FXN assignment" ; exit
fi



##############################################################################
## EXECUTE
##############################################################################
function singleMode {
  OUT1=${OUTPRE}.transcript-summaries.txt
  OUT2=${OUTPRE}.final-summary.txt
  if ${VERBOSE} ; then for VAR in OUT1 OUT2 FXN ; do echo -e "${VAR}\t${!VAR}" ; done ; fi
  ${FXN} > ${OUT1}
  finalSummary ${OUT1} > ${OUT2}
}

function fofnMode {
  while read line ; do
    ARR=( $( echo $line ) )
    export OUTPRE=${ARR[0]}
    export R1=${ARR[1]}
    export BAM=${R1} ## if bammode
    export R2=${ARR[2]}
    if $VERBOSE ; then echo -e "${OUTPRE}\t${R1}\t${R2}" ; date ; fi
    singleMode
  done < ${FOFN}  
}

if $FOFNMODE ; then
  fofnMode
else
  singleMode
fi
